name: Terraform Lint

on:
  push:
    paths:
      - 'main.tf'
      # Add other relevant paths if needed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Install tflint
      run: |
        curl -L $(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | jq -r .assets[].browser_download_url | grep linux_amd64) -o tflint.zip
        unzip tflint.zip
        chmod +x tflint
        sudo mv tflint /usr/local/bin/
        
    - name: Run tflint
      run: tflint

